### ISSUE TITLE
Help on getting started

### ISSUE THREAD

**Issue by Hosea987** [nixrajput/social-media-app-flutter#19]
Hi there,thanks for the awesome work,i am really learning a lot from your code. Can you give access to the back end code and  clear instructions on how to set up the backend. It would really help out plus we can also be able to add features too.

**Comment by nixrajput** [comment]
Hi

You can contact me at [Telegram](https://telegram.me/nixrajput) for further discussion.

Thanks.

**Comment by Hosea987** [comment]
@nixrajput thanks. just contacted you on telegram
