### ISSUE TITLE
What sdk flutter version u use on your project ?

### ISSUE THREAD

**Issue by rhtzy** [nixrajput/social-media-app-flutter#2]

**Comment by nixrajput** [comment]
- Flutter version 3.3.0
- Dart version 2.18.0
- DevTools version 2.15.0

> I always maintain to use the latest version of the SDK and upgrade regularly.

**Comment by rhtzy** [comment]
Thanks.

**Comment by nixrajput** [comment]
If you want to contribute to the project, you are heartedly welcome to my project.

Thanks
