### ISSUE TITLE
[Bug]: Can't Login

### ISSUE THREAD

**Issue by snoopyxz** [nixrajput/social-media-app-flutter#23]
### What happened?

Hi i already create an accounts mounths ago today I reinstalled the app to test it again but i can't login in my account I enter my account details and i click login and the app loading forever

### Version

1.0.1+31

### What devices are you seeing the problem on?

Android

### OS

Android 13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nixrajput** [comment]
Hi @snoopyxz,

Can you tell me if any error is coming on the screen during the login process?

Thnaks

**Comment by snoopyxz** [comment]
No error just loop 

https://github.com/nixrajput/social-media-app-flutter/assets/104867141/0f365499-9561-4c76-9361-e24e219dbce0

**Comment by nixrajput** [comment]
Please clean your app's data and then try again to log in.
