### ISSUE TITLE
Errors setup app 

### ISSUE THREAD

**Issue by snoopyxz** [nixrajput/social-media-app-flutter#3]
![imagem](https://user-images.githubusercontent.com/104867141/189751368-8eb9491a-fc0d-4f3f-ab84-5a9ed3a27604.png)
![imagem](https://user-images.githubusercontent.com/104867141/189751478-6cd8da5e-cfc0-4f51-a709-7e6c980d4314.png)
![imagem](https://user-images.githubusercontent.com/104867141/189751556-d2566a21-afd4-4f50-90ef-06a92ff4eb9e.png)

can you help me with this errors please.

**Comment by nixrajput** [comment]
You have to create a `secrets` file in the `constants` folder.

Steps to follow: 
- Create `secrets.dart` file in constants folder.
- Add the following code to the file.
```dart
abstract class AppSecrets {
  static const uploadPreset = 'XXXXXXXXXXXX';
  static const cloudinaryCloudName = 'XXXXXXXXXXXX';
  static const githubToken = 'XXXXXXXXXXXX ';
}
```
- Replace XXXXXXXXXXXX with your values in the file.
- Now run the following commands:
```dart
flutter clean
flutter pub get packages
```
- Now you are good to go.

**Comment by snoopyxz** [comment]
Who can i get "uploadPreset" value ?

**Comment by nixrajput** [comment]
Get it from Cloudinary settings or google search for it.

**Comment by snoopyxz** [comment]
thanks i got it.

**Comment by nixrajput** [comment]
Keep it open, in case anyone else faces this issue.

**Comment by zohaibjut** [comment]
documentations about secret file are not clear, please mention it here how to get these.
